services:
  watchtower:
    restart: unless-stopped
    image: containrrr/watchtower:arm64v8-latest
    container_name: mjl-watchtower
    command: --label-enable --interval 86400
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment: 
      WATCHTOWER_NOTIFICATION_REPORT: "true"
      WATCHTOWER_NOTIFICATION_URL: >
        discord://A0leSZwDJ2I2siEAboTwW0kxFWi5M0TJibbY_ONASC1vI_p-ZMuHAiZlinhNpVLnzt9l@1111231485270298695
      WATCHTOWER_NOTIFICATION_TEMPLATE: |
        {{- if .Report -}}
          {{- with .Report -}}
        {{len .Scanned}} Scanned, {{len .Updated}} Updated, {{len .Failed}} Failed
              {{- range .Updated}}
        - {{.Name}} ({{.ImageName}}): {{.CurrentImageID.ShortID}} updated to {{.LatestImageID.ShortID}}
              {{- end -}}
              {{- range .Fresh}}
        - {{.Name}} ({{.ImageName}}): {{.State}}
            {{- end -}}
            {{- range .Skipped}}
        - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
            {{- end -}}
            {{- range .Failed}}
        - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
            {{- end -}}
          {{- end -}}
        {{- else -}}
          {{range .Entries -}}{{.Message}}{{"\n"}}{{- end -}}
        {{- end -}}

  mjl-qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: mjl-qbittorrent
    labels: 
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - PLEX_UID=501
      - PLEX_GID=20
      - TZ=Europe/London
      - WEBUI_PORT=8081
      - TORRENTING_PORT=51413
    volumes:
      - /Users/mjl/.config/qbittorrent:/config
      - /Volumes/FilmArchive:/downloads
      - /Users/mjl/Music/Plex Library:/downloads/Music
    ports:
      - 8081:8081
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  # mjl-plex:
  mjl-plex-temp:
    restart: unless-stopped
    image: lscr.io/linuxserver/plex:arm64v8-latest
    # container_name: mjl-plex
    container_name: mjl-plex-temp
    labels: 
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - PUID=501
      - PGID=20
      - TZ=Europe/London
      - VERSION=docker
      # - UMASK=777
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - /Users/mjl/Plex/config:/config
      # - /Volumes/Films:/mnt/Films
      # - /Volumes/FilmArchive:/mnt/Films
      - /Users/mjl/Music/Audiobooks:/mnt/Audiobooks
      - /Users/mjl/Music/Radio/Mark Steel:/mnt/Radio/Mark Steel
      - /Users/mjl/Music/Plex Library:/mnt/Music
