! Theming
rofi.width:           60
rofi.opacity:         90
rofi.bw:              0
rofi.font:            Roboto 10
rofi.terminal:        urxvt
rofi.location:        0
rofi.padding:         20
rofi.yoffset:         0
rofi.xoffset:         0
rofi.separator-style: solid
rofi.lines:           10
rofi.columns:         1
rofi.fixed-num-lines: true

! MJL Theme Colours

! State:           'bg',     'fg',     'bgalt',  'hlbg',   'hlfg'
!rofi.color-normal: #1c2230,  #676e7d,  #1c2230,  #c73b18,  #f3f4f5

!                  background 'border'
!rofi.color-window: #1c2230,   #1c2230

! Gooey Theme Colours (base16-builder)
! State:           'bg',    'fg',    'bgalt', 'hlbg',  'hlfg'
rofi.color-normal: #101218, #ffffff, #101218, #ffffff, #101218
rofi.color-urgent: #101218, #ee829f, #101218, #ee829f, #101218
rofi.color-active: #101218, #97bbf7, #101218, #97bbf7, #101218
!                  'bg',    'border'
rofi.color-window: #101218, #ffffff
