out_to_x no
own_window no
out_to_console yes
max_text_width 0
update_interval 0.5
background no

#Colour scheme - base16-gooey
#base00: "101218"
#base01: "1f222d"
#base02: "252936"
#base03: "7780a1"
#base04: "C0C5CE"
#base05: "d1d4e0"
#base06: "C9CCDB"
#base07: "ffffff"
#base08: "ee829f"
#base09: "f99170"
#base0A: "ffefcc"
#base0B: "a5ffe1"
#base0C: "97e0ff"
#base0D: "97bbf7"
#base0E: "c0b7f9"
#base0F: "fcc09e"


TEXT
[
{"full_text":"${if_running cmus}${if_match "${execi 1 ~/.i3/cmus.sh -H}" == "playing"}${execi 1 ~/.i3/cmus.sh -D}${endif}${endif}","color":"\#a5ffe1","separator":true,"separator_block_width":15},\
{"full_text":"${if_running spotify}${execi 1 ~/.i3/spotify.sh -D}${endif}","color":"\#a5ffe1","separator":true,"separator_block_width":15},\

{"full_text":"","color":"\#ee829f","separator":false,"separator_block_width":6},\
{"full_text":"${exec amixer sget Master | grep Left: | cut -d " " -f7} ","color":"\#ffffff","separator":true,"separator_block_width":15},\

{"full_text":"","color":"\#7780a1","separator":false,"separator_block_width":6},\
{"full_text":"${cpu cpu0}%","color":"\#ffffff","separator":true,"separator_block_width":15},\

{"full_text":"","color":"\#c0b7f9","separator":false,"separator_block_width":6},\
{"full_text":"${addr enp4s0}","color":"\#ffffff","separator":true,"separator_block_width":15},\

{"full_text":"","color":"\#6096BF","separator":false,"separator_block_width":6},\
{"full_text":"${time %a %d %b %Y}","color":"\#ffffff","separator":false,"separator_block_width":6},\

{"full_text":"","color":"\#97e0ff","separator":false,"separator_block_width":6},\
{"full_text":"${time %T}","color":"\#ffffff","separator":${if_match "${execi 1 ~/.scripts/update_count.sh -H}" != "0"}true${else}false${endif}},\

{"full_text":"${if_match "${execi 1200 ~/.scripts/update_count.sh -H}" != "0"}${endif}","color":"\#f99170","separator":false,"separator_block_width":6},\
{"full_text":"${if_match "${execi 1200 ~/.scripts/update_count.sh -H}" != "0"}${execi 1200 ~/.scripts/update_count.sh -D}${endif}","color":"\#97e0ff","separator":true,"separator_block_width":15}\
],
