out_to_x no
own_window no
out_to_console yes
max_text_width 0
update_interval 1
background no

TEXT
[

{"full_text":"${if_running cmus}${execi 1 ~/.i3/cmus.sh -D}${endif}","color":"\#00FF00","separator":true,"separator_block_width":15},\
{"full_text":"${if_running spotify}${execi 1 ~/.i3/spotify.sh -D}${endif}","color":"\#00FF00","separator":true,"separator_block_width":15},\

{"full_text":"","color":"\#BF4D80","separator":false,"separator_block_width":6},\
{"full_text":"${exec amixer -c 2 | grep Left: | cut -d " " -f7} ","color":"\#C0C0C0","separator":true,"separator_block_width":15},\

{"full_text":"","color":"\#395573","separator":false,"separator_block_width":6},\
{"full_text":"${if_match ${cpu cpu0}<25}${cpu cpu0}","color":"\#C0C0C0","separator":false,"separator_block_width":0},\
{"full_text":"${else}"},\
{"full_text":"${if_match ${cpu cpu0}<50}${cpu cpu0}","color":"\#008000","separator":false,"separator_block_width":0},\
{"full_text":"${else}"},\
{"full_text":"${if_match ${cpu cpu0}<75}${cpu cpu0}","color":"\#ff2500","separator":false,"separator_block_width":0},\
{"full_text":"${else}"},\
{"full_text":"${if_match ${cpu cpu0}<=100}${cpu cpu0}","color":"\#FF3333","separator":false,"separator_block_width":0},\
{"full_text":"${endif}${endif}${endif}${endif}"},\
{"full_text":"%","color":"\#C0C0C0 ","separator":true,"separator_block_width":15},\

{"full_text":"","color":"\#7E62B3","separator":false,"separator_block_width":6},\
{"full_text":"${addr enp4s0}","color":"\#C0C0C0","separator":true,"separator_block_width":15},\

{"full_text":"","color":"\#6096BF","separator":false,"separator_block_width":6},\
{"full_text":"${time %a %d %b %Y}","color":"\#C0C0C0","separator":false,"separator_block_width":6},\

{"full_text":"","color":"\#A37079","separator":false,"separator_block_width":6},\
{"full_text":"${time %T}","color":"\#C0C0C0","separator":false}\

],
